### ISSUE TITLE
ValueComparator.compare() :: compare currency case

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-darmonlyone#8]
If you want to compare the currency, you shouldn't compare only the first letters.
What will happen if you compare "YUAN" (Chinese currency) and "YEN" (Japanese currency) ?

**HINT:** [String](https://docs.oracle.com/javase/9/docs/api/java/lang/String.html) has a method that can compare 2 string alphabetically

https://github.com/OOP2018/coinpurse-darmonlyone/blob/332e99ccefe241fdeb17e440ea8b4c28995abf4f/src/coinpurse/ValueComparator.java#L24-L31

**Comment by darmonly** [comment]
I'm not sure, method that I use is what you mean. Please recheck this issue that i fix again.

**Comment by chinnonae** [comment]
Have you push your code to Github?

**Comment by darmonly** [comment]
Oh, sorrybi foget to push my code
